FROM golang:alpine
RUN apk add --no-cache git curl openssh

WORKDIR "/go"

RUN curl https://glide.sh/get | sh
RUN go get -u \
    golang.org/x/tools/cmd/godoc \
    github.com/DATA-DOG/godog/cmd/godog \
    github.com/DATA-DOG/godog \
    cmd/gofmt \
    golang.org/x/tools/cmd/goimports \
    github.com/golang/lint/golint \
    github.com/vattle/sqlboiler \
    github.com/rubenv/sql-migrate

    RUN mkdir /root/.ssh && echo "StrictHostKeyChecking no " > /root/.ssh/config
