FROM golang:1.8-alpine
RUN apk add --no-cache git curl

WORKDIR "/go"

RUN curl https://glide.sh/get | sh
RUN go get -u \
    golang.org/x/tools/cmd/godoc \
    github.com/DATA-DOG/godog/cmd/godog \
    github.com/DATA-DOG/godog \
    cmd/gofmt \
    golang.org/x/tools/cmd/goimports \
    github.com/golang/lint/golint
