FROM golang:alpine
RUN apk add --no-cache git curl
RUN apk update && apk add openssh
RUN mkdir /root/.ssh && echo "StrictHostKeyChecking no " > /root/.ssh/config

WORKDIR "/go"

RUN curl https://glide.sh/get | sh
RUN go get -u \
    golang.org/x/tools/cmd/godoc \
    github.com/DATA-DOG/godog/cmd/godog \
    github.com/DATA-DOG/godog \
    cmd/gofmt \
    golang.org/x/tools/cmd/goimports \
    github.com/golang/lint/golint
